import tokens from '@/tokens/base';

/** MUI Theme typography 变体 sx 预设 — 对应 TypographyVariantsOptions */
export const typography = {
  heading1: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '2.25rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  heading2: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '2rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  subtitle1: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.75rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  subtitle2: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.5rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  subtitle3: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.25rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  body1: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  body1Highlight: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  body2: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  body2Highlight: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  body3: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '0.875rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  body3Highlight: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '0.875rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  ctaButton1: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  ctaButton2: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  ctaIconButton: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  ctaLink: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  tabHighlight: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.25rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  tabDefault: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  inputFieldTitle: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  inputFieldPlaceholder: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  label1: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1.125rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  label2: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1rem',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  label3: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: '1rem',
    fontWeight: tokens.fontWeightRegular,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
  searchHighlight: {
    fontFamily: tokens.fontFamilyBody,
    fontSize: 'inherit',
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight120,
    letterSpacing: 0,
  },
} as const;
